import type { VisualAsset } from "./visualAssetManifest";

export const deliveredIntelDocumentVisuals: Record<string, VisualAsset> = {
  "I02": {
    id: "i02_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-vienna-internal-memo.png",
    alt: "Vienna internal memo / Austrian war council intelligence document",
    caption: "Vienna internal memo / Austrian war council",
    fallback: "document-placeholder",
  },
  "I04": {
    id: "i04_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-blank-check-telegram.png",
    alt: "Blank check telegram intelligence document",
    caption: "Blank check telegram",
    fallback: "document-placeholder",
  },
  "I30": {
    id: "i30_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-british-cabinet-note.png",
    alt: "British cabinet note intelligence document",
    caption: "British cabinet note",
    fallback: "document-placeholder",
  },
  "I22": {
    id: "i22_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-russian-mobilization-memo.png",
    alt: "Russian mobilization memo intelligence document",
    caption: "Russian mobilization memo",
    fallback: "document-placeholder",
  },
  "I16": {
    id: "i16_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-serbian-reply-dossier.png",
    alt: "Serbian reply dossier intelligence document",
    caption: "Serbian reply dossier",
    fallback: "document-placeholder",
  },
  "I29": {
    id: "i29_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-belgium-neutrality-treaty.png",
    alt: "Belgium neutrality treaty intelligence document",
    caption: "Belgium neutrality treaty",
    fallback: "document-placeholder",
  },
  "I23": {
    id: "i23_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-german-general-staff-map.png",
    alt: "German general staff map intelligence document",
    caption: "German general staff map",
    fallback: "document-placeholder",
  },
  "I12": {
    id: "i12_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-press-nationalist-headlines.png",
    alt: "Press nationalist headlines intelligence document",
    caption: "Press nationalist headlines",
    fallback: "document-placeholder",
  },
  "I15": {
    id: "i15_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-hague-arbitration-file.png",
    alt: "Hague arbitration file intelligence document",
    caption: "Hague arbitration file",
    fallback: "document-placeholder",
  },
  "I26": {
    id: "i26_delivered_document",
    kind: "intel_document",
    src: "/assets/intel-documents/intel-schlieffen-risk-brief.png",
    alt: "Schlieffen risk brief intelligence document",
    caption: "Schlieffen risk brief",
    fallback: "document-placeholder",
  },
};
